# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'SC_DGOIT-Pipelines'
    subscriptionId: '5678ffbf-fd6c-4c9c-bbbe-8d4367eb6ea4'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'test-01-ok-rg'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/oliverkutschenreutercom/AzureRmPipeline-repo/main/CreateWebApp/azuredeploy.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'